// packages/payment-gateway/examples/nextjs/payment-form.tsx
/**
 * Example Payment Form Component for Next.js
 */

'use client';

import { useState } from 'react';
import { paymentGateway } from './payment-gateway';
import { PaymentError } from '@your-org/payment-gateway';

export default function PaymentForm() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [cardDetails, setCardDetails] = useState({
    number: '',
    expMonth: '',
    expYear: '',
    cvc: ''
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      // Set the active gateway (could come from user selection or API)
      paymentGateway.setActiveGateway('Stripe');

      // Create payment token
      const { token, gatewayName } = await paymentGateway.createPaymentToken(
        cardDetails,
        'Stripe'
      );

      console.log('Payment token created:', token);
      console.log('Gateway used:', gatewayName);

      // Send token to your backend for processing
      const response = await fetch('/api/process-payment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          paymentToken: token,
          gateway: gatewayName,
          amount: 1000 // amount in cents
        })
      });

      if (!response.ok) {
        throw new Error('Payment processing failed');
      }

      alert('Payment successful!');
    } catch (err) {
      if (err instanceof PaymentError) {
        setError(`Payment error: ${err.message}`);
      } else {
        setError('An unexpected error occurred');
      }
      console.error('Payment failed:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label htmlFor="cardNumber">Card Number</label>
        <input
          id="cardNumber"
          type="text"
          value={cardDetails.number}
          onChange={(e) => setCardDetails({ ...cardDetails, number: e.target.value })}
          placeholder="4111111111111111"
          required
        />
      </div>

      <div className="flex gap-4">
        <div>
          <label htmlFor="expMonth">Month</label>
          <input
            id="expMonth"
            type="text"
            value={cardDetails.expMonth}
            onChange={(e) => setCardDetails({ ...cardDetails, expMonth: e.target.value })}
            placeholder="12"
            maxLength={2}
            required
          />
        </div>

        <div>
          <label htmlFor="expYear">Year</label>
          <input
            id="expYear"
            type="text"
            value={cardDetails.expYear}
            onChange={(e) => setCardDetails({ ...cardDetails, expYear: e.target.value })}
            placeholder="2025"
            maxLength={4}
            required
          />
        </div>

        <div>
          <label htmlFor="cvc">CVC</label>
          <input
            id="cvc"
            type="text"
            value={cardDetails.cvc}
            onChange={(e) => setCardDetails({ ...cardDetails, cvc: e.target.value })}
            placeholder="123"
            maxLength={4}
            required
          />
        </div>
      </div>

      {error && <div className="text-red-600">{error}</div>}

      <button
        type="submit"
        disabled={loading}
        className="bg-blue-600 text-white px-6 py-2 rounded disabled:opacity-50"
      >
        {loading ? 'Processing...' : 'Pay Now'}
      </button>
    </form>
  );
}

// packages/payment-gateway/examples/angular/payment-form.component.ts
/**
 * Example Payment Form Component for Angular
 */

import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { PaymentGatewayService } from './payment-gateway.service';
import { PaymentError, GatewayName } from '@your-org/payment-gateway';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-payment-form',
  template: `
    <form [formGroup]="paymentForm" (ngSubmit)="handleSubmit()" class="payment-form">
      <div class="form-group">
        <label for="cardNumber">Card Number</label>
        <input
          id="cardNumber"
          type="text"
          formControlName="number"
          placeholder="4111111111111111"
          class="form-control"
        />
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="expMonth">Month</label>
          <input
            id="expMonth"
            type="text"
            formControlName="expMonth"
            placeholder="12"
            maxlength="2"
            class="form-control"
          />
        </div>

        <div class="form-group">
          <label for="expYear">Year</label>
          <input
            id="expYear"
            type="text"
            formControlName="expYear"
            placeholder="2025"
            maxlength="4"
            class="form-control"
          />
        </div>

        <div class="form-group">
          <label for="cvc">CVC</label>
          <input
            id="cvc"
            type="text"
            formControlName="cvc"
            placeholder="123"
            maxlength="4"
            class="form-control"
          />
        </div>
      </div>

      <div *ngIf="error" class="alert alert-danger">
        {{ error }}
      </div>

      <button
        type="submit"
        [disabled]="loading || paymentForm.invalid"
        class="btn btn-primary"
      >
        {{ loading ? 'Processing...' : 'Pay Now' }}
      </button>
    </form>
  `,
  styles: [`
    .payment-form {
      max-width: 500px;
      margin: 20px auto;
    }

    .form-group {
      margin-bottom: 15px;
    }

    .form-row {
      display: flex;
      gap: 10px;
    }

    .form-control {
      width: 100%;
      padding: 8px;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    .btn-primary {
      background-color: #007bff;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }

    .btn-primary:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .alert-danger {
      color: #721c24;
      background-color: #f8d7da;
      border: 1px solid #f5c6cb;
      padding: 12px;
      border-radius: 4px;
      margin-bottom: 15px;
    }
  `]
})
export class PaymentFormComponent {
  paymentForm: FormGroup;
  loading = false;
  error: string | null = null;

  constructor(
    private fb: FormBuilder,
    private paymentGateway: PaymentGatewayService,
    private http: HttpClient
  ) {
    this.paymentForm = this.fb.group({
      number: ['', Validators.required],
      expMonth: ['', [Validators.required, Validators.pattern(/^\d{1,2}$/)]],
      expYear: ['', [Validators.required, Validators.pattern(/^\d{4}$/)]],
      cvc: ['', [Validators.required, Validators.pattern(/^\d{3,4}$/)]]
    });
  }

  async handleSubmit() {
    if (this.paymentForm.invalid) {
      return;
    }

    this.loading = true;
    this.error = null;

    try {
      const cardDetails = this.paymentForm.value;

      // Set the active gateway
      const gateway: GatewayName = 'Stripe';
      this.paymentGateway.setActiveGateway(gateway);

      // Create payment token
      const { token, gatewayName } = await this.paymentGateway.createPaymentToken(
        cardDetails,
        gateway
      );

      console.log('Payment token created:', token);
      console.log('Gateway used:', gatewayName);

      // Send token to backend for processing
      const response = await this.http.post('/api/process-payment', {
        paymentToken: token,
        gateway: gatewayName,
        amount: 1000 // amount in cents
      }).toPromise();

      alert('Payment successful!');
      this.paymentForm.reset();
    } catch (err) {
      if (err instanceof PaymentError) {
        this.error = `Payment error: ${err.message}`;
      } else {
        this.error = 'An unexpected error occurred';
      }
      console.error('Payment failed:', err);
    } finally {
      this.loading = false;
    }
  }
}
